platform :ios, '11.0'

target 'Example' do
  use_frameworks!

  # Pods for Example
  pod 'PickImageAlert', :git => 'https://github.com/limadeveloper/PickImageAlert.git', :branch => 'feature/spm_support'

end