platform :ios, '11.0'

target 'PickImageAlert' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for PickImageAlert
  pod 'SwiftLint', '~> 0.28'

  target 'PickImageAlertTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
