# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

min_fastlane_version("2.108.0")
default_platform(:ios)

platform :ios do
  desc "Build and run tests"
  lane :build do
    begin
      test_lane()
      success_build()
    rescue => exception
      on_error(exception)
    end
  end
end

### Methods
def test_lane
  cocoapods
  clear_derived_data
  scan
  slather
  swiftlint(
    mode: :lint,      
    output_file: "swiftlint.result.json", 
    executable: "./Pods/SwiftLint/swiftlint"
  )
end

def on_error(exception)
  slack(
    message: "Something goes wrong",
    success: false,
    slack_url: "https://hooks.slack.com/services/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",
    payload: {
      "Build Date" => Time.new.to_s
    },
    attachment_properties: {
      fields: [
        {
          title: "Version number",
          value: get_version_number,
        },
        {
          title: "Build number",
          value: get_build_number,
        },
        {
          title: "Last git tag",
          value: last_git_tag,
        },
        {
          title: "Error message",
          value: exception.to_s,
          short: false
        }
      ]
    }
  )
end

def success_build
  slack(
    message: "All tests have been successful",
    success: true,
    slack_url: "https://hooks.slack.com/services/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",
    payload: {
      "Build Date" => Time.new.to_s
    },
    attachment_properties: {
      fields: [
        {
          title: "Version number",
          value: get_version_number,
        },
        {
          title: "Build number",
          value: get_build_number,
        },
        {
          title: "Last git tag",
          value: last_git_tag,
        }
      ]
    }
  )
end